### ISSUE TITLE
Problems when using in tandem w FRC

### ISSUE THREAD

**Issue by LindyLo** [Instagram/IGInterfaceDataTable#16]
When using your class together with NSFetchedResultsController, problem occurs when inserting new items.

**Comment by rnystrom** [comment]
Thanks for reporting this @LindyLo! Could you provide some details, maybe even a sample project about what troubles you're running into? To be fair, I haven't tried using our project alongside `NSFetchedResultsController` before, so I'm sure there are some problems that we should fix.

**Comment by bassrock** [comment]
I receive the same issue the error is a range exception on new insert:

```*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSMutableArray insertObjects:atIndexes:]: index 11 in index set beyond bounds [0 .. 1]'```

**Comment by bassrock** [comment]
However if I remove the Insert part of the ```NSFetchedResultsController``` it seems like it works.

On this note though this project helped me greatly improve my WatchKit app performance as I was reloading all the table rows before. This project is a great candidate to get NSFetchedResultsController working great with WatchKit.

**Comment by LindyLo** [comment]
Thank you for reply ! 
I've made sample project that shows problem 
https://github.com/LindyLo/IGInterfaceTableDataSource-FRC-Problem
UI is self explanatory, just run WatchKit App

**Comment by rnystrom** [comment]
Wow, thanks for the sample project! Looking into this ASAP.

@bassrock totally agree. Getting this working out-of-the-box with FRC would be a huge win!

**Comment by rnystrom** [comment]
PR up w/ a fix. Really good find and kind of fun to hunt down. Not to mention it gave me a way to solve the unit tests issue! Thanks @LindyLo and @bassrock for the help :+1:

**Comment by LindyLo** [comment]
Tried updated code - it works like a charm now, thank you so much  !!!
I'm glad I was able to help :)
